name:                poisonedWells
version:             0.1.0.0
github:              "pertain/poisonedWells"
license:             MIT
author:              "William Ersing"
maintainer:          "example@example.com"
copyright:           "2021 William Ersing"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/pertain/poisonedWells#readme>

dependencies:
- base >= 4.7 && < 5
- vector
- containers
- random

library:
  source-dirs: src

executables:
  poisonedWells:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - poisonedWells

tests:
  poisonedWells-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - poisonedWells
